### ISSUE TITLE
Header examples

### ISSUE THREAD

**Issue by irsdl** [bitquark/shortscan#1]
Could you please add more examples to the README about adding multiple headers or how to send a request to an IP with a different HOST header?

**Comment by bitquark** [comment]
You can add multiple headers by using `-H` multiple times (e.g. `shortscan -H One: abc -H Two: def ...`). It's documented in `--help` but I'll update the readme too.

Regarding setting a different `Host` header, it looks like the HTTP library doesn't overwrite it when provided with a new header value, I'll take a look and see what I can do!

**Comment by bitquark** [comment]
I've added some code to handle setting the `Host` header and added some additional examples to the documentation. That should to the trick!
