### ISSUE TITLE
bypass 403 IIS 

### ISSUE THREAD

**Issue by wesamlibya** [bitquark/shortscan#12]
Is there any way to bypass 403? I have used many tools but it did not work. Any tip?

<img width="1280" alt="bypass 403 IIS" src="https://github.com/bitquark/shortscan/assets/95371893/08950c2a-bbee-4260-8ec3-11ac0906741c">

**Comment by meme-lord** [comment]
The shortscan technique does work on 403 pages but it wont "bypass" them whatever that's supposed to mean. In the case of the screenshot the 403 happens because directory listing is not enabled.

**Comment by bitquark** [comment]
As @meme-lord says this error is a standard message when directory listing is disabled. The best you can do is to run the tool against the directory and see what it turns up.
