### ISSUE TITLE
scan result 

### ISSUE THREAD

**Issue by fawzianaas03** [bitquark/shortscan#17]
🌀 Shortscan v0.9.0 · an IIS short filename enumeration tool by bitquark
FATAL Unable to access server                       error="Get \"https://example.com/.aspx\": context deadline exceeded (Client.Tim
why the scan result is like that ?

**Comment by bitquark** [comment]
This generally means that the server you tried to access is taking too long to respond. If you can provide a specific example I may be able to check whether this is expected. I'll close this until then.
