### ISSUE TITLE
go Install doesn't install shortscan

### ISSUE THREAD

**Issue by JRL-WF** [bitquark/shortscan#19]
I've tried installing but was unsuccessful, Kindly crosscheck.

**Comment by D47K-0v3771D3** [comment]
I checked their Releases, it was empty...

**Comment by meme-lord** [comment]
Works for me. What go version are you running?
Is there output when you run ```go install github.com/bitquark/shortscan/cmd/shortscan@latest```?
Check your ~/go/bin folder it should be there. Your problem is likely that your go bin folder is not part of your PATH. You can fix this by adding ```export PATH=$PATH:~/go/bin``` to your .bashrc file.
