### ISSUE TITLE
results in a DoS of target

### ISSUE THREAD

**Issue by mreyelidz** [bitquark/shortscan#2]
$> shortscan target.url

access to target via web browser and via ping indicate server is up and running prior to scan

Shortscan v0.5 · an IIS short filename enumeration tool by bitquark
Target: xxxxxxxxxxxxxxxxxxxx
Running: Microsoft-IIS/7.5 (ASP.NET v4.0.30319)
Vulnerable: Yes!
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Finished! Requests: 722; Retries: 0; Sent 139614 bytes; Received 274905 bytes

no shortnames are found and after running scan, and now the website is not reachable from my machine via ping or web browser.

isitdownrightnow.com also reports site as down

**Comment by bitquark** [comment]
If the server is getting overwhelmed with requests I'd suggest using the `--concurrency` option to set a lower request rate (default is 20 concurrent requests)
