### ISSUE TITLE
Shortscan location

### ISSUE THREAD

**Issue by nigawtester** [bitquark/shortscan#7]
Hey :)
Just adding this here for next time I have the same issue!
Once I installed shortscan, I couldn't run it just by typing shortscan but I had to type:
`$HOME/go/bin/shortscan`

**Comment by bitquark** [comment]
What @meme-lord said :slightly_smiling_face:

**Comment by nigawtester** [comment]
Yeah got it. I was using an old system that had some misconfig. It's all good now, thanks!
